In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [34]:
df=pd.read_csv(r"C:\Users\LENOVO\Downloads\Decision Tree Classifier.csv")
df.head()

,Customer_ID,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,569,Female,No,0,Graduate,No,2378,0.0,9,360,1,Urban,N
1,15,Male,Yes,2,Graduate,No,1299,1086.0,17,120,1,Urban,Y
2,95,Male,No,0,Not Graduate,No,3620,0.0,25,120,1,Semiurban,Y
3,134,Male,Yes,0,Graduate,Yes,3459,0.0,25,120,1,Semiurban,Y
4,556,Male,Yes,1,Graduate,No,5468,1032.0,26,360,1,Semiurban,Y

In [35]:
df["Gender"]=df["Gender"].map({"Male":0,"Female":1})
df

,Customer_ID,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,569,1,No,0,Graduate,No,2378,0.0,9,360,1,Urban,N
1,15,0,Yes,2,Graduate,No,1299,1086.0,17,120,1,Urban,Y
2,95,0,No,0,Not Graduate,No,3620,0.0,25,120,1,Semiurban,Y
3,134,0,Yes,0,Graduate,Yes,3459,0.0,25,120,1,Semiurban,Y
4,556,0,Yes,1,Graduate,No,5468,1032.0,26,360,1,Semiurban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,480,0,Yes,2,Graduate,No,2947,1603.0,10,360,1,Urban,N
610,525,0,No,0,Graduate,No,4680,2087.0,15,360,1,Semiurban,N
611,551,0,Yes,2,Graduate,Yes,6633,0.0,25,360,0,Rural,N
612,552,0,Yes,1,Not Graduate,No,2492,2375.0,30,360,1,Rural,Y
613,606,0,Yes,0,Not Graduate,No,2400,3800.0,25,180,1,Urban,N

In [36]:
df["Married"]=df["Married"].map({"No":0,"Yes":1})
df.head()

,Customer_ID,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,569,1,0,0,Graduate,No,2378,0.0,9,360,1,Urban,N
1,15,0,1,2,Graduate,No,1299,1086.0,17,120,1,Urban,Y
2,95,0,0,0,Not Graduate,No,3620,0.0,25,120,1,Semiurban,Y
3,134,0,1,0,Graduate,Yes,3459,0.0,25,120,1,Semiurban,Y
4,556,0,1,1,Graduate,No,5468,1032.0,26,360,1,Semiurban,Y

In [37]:
df["Education"]=df["Education"].map({"Graduate":1,"Not Graduate":0})
df.head()

,Customer_ID,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,569,1,0,0,1,No,2378,0.0,9,360,1,Urban,N
1,15,0,1,2,1,No,1299,1086.0,17,120,1,Urban,Y
2,95,0,0,0,0,No,3620,0.0,25,120,1,Semiurban,Y
3,134,0,1,0,1,Yes,3459,0.0,25,120,1,Semiurban,Y
4,556,0,1,1,1,No,5468,1032.0,26,360,1,Semiurban,Y

In [38]:
df["Self_Employed"]=df["Self_Employed"].map({"Yes":1,"No":0})
df.head()

,Customer_ID,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,569,1,0,0,1,0,2378,0.0,9,360,1,Urban,N
1,15,0,1,2,1,0,1299,1086.0,17,120,1,Urban,Y
2,95,0,0,0,0,0,3620,0.0,25,120,1,Semiurban,Y
3,134,0,1,0,1,1,3459,0.0,25,120,1,Semiurban,Y
4,556,0,1,1,1,0,5468,1032.0,26,360,1,Semiurban,Y

In [39]:
df["Property_Area"]=df["Property_Area"].map({"Urban":1,"Semiurban":0})
df.head()

,Customer_ID,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,569,1,0,0,1,0,2378,0.0,9,360,1,1.0,N
1,15,0,1,2,1,0,1299,1086.0,17,120,1,1.0,Y
2,95,0,0,0,0,0,3620,0.0,25,120,1,0.0,Y
3,134,0,1,0,1,1,3459,0.0,25,120,1,0.0,Y
4,556,0,1,1,1,0,5468,1032.0,26,360,1,0.0,Y

In [40]:
df["Loan_Status"]=df["Loan_Status"].map({"Y":1,"N":0})
df.head()

,Customer_ID,Gender,Married,Dependents,Education,Self_Employed,Applicant_Income,Coapplicant_Income,Loan_Amount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,569,1,0,0,1,0,2378,0.0,9,360,1,1.0,0
1,15,0,1,2,1,0,1299,1086.0,17,120,1,1.0,1
2,95,0,0,0,0,0,3620,0.0,25,120,1,0.0,1
3,134,0,1,0,1,1,3459,0.0,25,120,1,0.0,1
4,556,0,1,1,1,0,5468,1032.0,26,360,1,0.0,1

In [41]:
x=df[["Customer_ID","Gender","Married","Dependents","Education","Self_Employed","Applicant_Income","Coapplicant_Income","Loan_Amount","Loan_Amount_Term","Credit_History","Property_Area"]]
y=df[["Loan_Status"]]
y

     Loan_Status
0              0
1              1
2              1
3              1
4              1
..           ...
609            0
610            0
611            0
612            1
613            0

[614 rows x 1 columns]

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=DecisionTreeClassifier()

In [45]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [46]:
prediction=model.predict(x_test)

In [47]:
accuracy=accuracy_score(y_test,prediction)

In [48]:
accuracy

0.6747967479674797