In [1]:
#simple linear regression
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
df=pd.read_csv(r"C:\Users\LENOVO\Downloads\Simple Linear Regression.csv")

In [3]:
df.head()

,Building Type,Square Footage,Number of Occupants,Appliances Used,Average Temperature,Day of Week,Energy Consumption
0,Residential,7063,76,10,29.84,Weekday,2713.95
1,Commercial,44372,66,45,16.72,Weekday,5744.99
2,Industrial,19255,37,17,14.30,Weekend,4101.24
3,Residential,13265,14,41,32.82,Weekday,3009.14
4,Commercial,13375,26,18,11.92,Weekday,3279.17

In [4]:
x=df[["Square Footage"]]
y=df["Energy Consumption"]
model=LinearRegression()
model.fit(x,y)
prediction=model.predict(x)
prediction

array([3235.37961113, 5122.93908987, 3852.20464436, 3549.15494382,
       3554.7201303 , 4769.04382187, 4832.84109606, 4646.25557092,
       4382.71869443, 3761.74506764, 4279.560374  , 5269.30349449,
       3846.33590225, 3779.604257  , 5198.6256261 , 3362.62001128,
       3096.09817113, 4823.12731601, 3255.46487509, 3428.49158225,
       4796.11086524, 3621.70473857, 3802.57329941, 4087.10610674,
       4977.53594474, 4964.38186758, 4679.69728245, 5390.11863388,
       4408.92566353, 4247.6870332 , 3560.99361325, 5243.19771061,
       4038.18305825, 4362.48165266, 3070.29594287, 5361.837368  ,
       3404.35890993, 4492.90938688, 2971.18503079, 5012.44484179,
       3936.44133074, 3489.86041142, 4286.79511643, 4741.47085246,
       5162.90724737, 3591.65273154, 4644.43423716, 3688.79053205,
       5359.25714517, 4390.66173333, 3516.26975094, 3045.40438149,
       4650.35357188, 3040.49689886, 3409.06402215, 5407.5224898 ,
       4835.82605972, 4723.86462612, 4324.33482892, 4339.15846202,
       3260.47354293, 3211.44930924, 5130.83153616, 3196.1703427 ,
       3365.09904889, 4743.29218622, 3225.05871983, 4698.77069432,
       3798.07055762, 4680.81031974, 5172.87399045, 4716.32632805,
       3477.26285292, 3508.12434162, 3565.14220682, 4265.69800038,
       3687.72808735, 5324.24706291, 4794.4919019 , 5265.05371572,
       3565.44576244, 3630.96318518, 5359.00418215, 4976.11935181,
       3919.18925263, 4182.32138828, 5150.10731845, 2992.33273944,
       3214.68723592, 3551.07746279, 4202.71020786, 3709.48290726,
       3119.01662094, 4376.84995232, 5122.38257122, 2906.37590451,
       3320.47637179, 3110.26410037, 3881.90250316, 4910.14659563,
       3733.31202395, 3416.70350541, 3129.48929006, 3014.23933716,
       2927.67539098, 3216.15442145, 3220.85953366, 4504.74805632,
       3853.8236077 , 2948.82309963, 3836.72330741, 4003.93186505,
       4568.89947874, 4156.11441918, 4918.19081974, 4744.75937175,
       5226.40096593, 4017.13653481, 3761.3403268 , 4887.27873843,
       5078.87293141, 3272.00865674, 3735.99343198, 4912.42326283,
       3206.08649317, 4977.43475953, 3923.89436484, 3338.48733896,
       3779.95840523, 3488.24144808, 3478.1735198 , 4135.92797001,
       3334.3387454 , 3192.93241601, 5104.77634488, 4421.87737026,
       5389.76448564, 5352.17418055, 3359.53386241, 4389.64988124,
       3827.71782382, 4601.83526423, 3338.18378334, 4233.52110396,
       5184.05495603, 3612.9016254 , 4220.215249  , 3867.78716653,
       3562.30902097, 3793.06188978, 4467.00597342, 4722.34684798,
       4659.25787026, 3909.88021341, 5325.81543364, 3495.2738201 ,
       4958.96845891, 3949.44363008, 3443.77054879, 3040.34512105,
       3022.38474647, 3358.47141771, 3619.37747877, 4943.68949237,
       4623.89363976, 4517.0420592 , 4911.10785512, 4788.67375239,
       4108.50677841, 4414.3390722 , 3282.32954804, 4347.30387133,
       3949.08948185, 4501.96546308, 4087.7638106 , 3764.88180911,
       3308.43533193, 4707.42202967, 3333.47867112, 4922.74415414,
       3574.24887561, 3586.6946563 , 2952.31398934, 3551.33042581,
       5212.79155534, 4419.55011046, 3355.73941707, 4323.52534725,
       4227.44999143, 4157.58160471, 4022.24638786, 4584.33022309,
       3024.56022846, 4288.36348717, 5072.44767065, 4521.6459862 ,
       5108.4190124 , 3572.22517144, 4727.65907145, 3963.4071889 ,
       5398.06167277, 4256.43955377, 3246.50998411, 5297.73653818,
       3734.17209822, 4355.65165106, 3212.76471695, 3991.58726957,
       3059.82327375, 3681.15104878, 3405.01661379, 3343.74896982,
       4390.86410375, 3268.31539662, 4135.47263658, 4358.83898514,
       5157.4938387 , 3780.7678869 , 3678.26727033, 4637.04771691,
       3314.40525925, 3161.81796429, 4696.44343451, 5157.08909786,
       3905.88339766, 4623.33712111, 3680.34156711, 3093.66972612,
       3340.76400616, 3691.42134748, 4125.65767132, 5323.58935905,
       4121.45848515, 3475.18855614, 3694.91223718, 3468.51033235,
       3777.3275898 , 4062.46750838, 5072.75122628, 4248.49651488,
       4620.09919443, 3525.52819755, 3679.58267804, 3381.23808971,
       4018.50253513, 3641.79000253, 4947.83808593, 5153.74998597,
       4592.98155845, 4696.08928628, 2944.52272825, 3297.10258854,
       3010.24252141, 3432.38721279, 4664.01357507, 4080.37729035,
       4501.30775922, 3092.45550361, 5361.63499758, 3244.1827243 ,
       3706.5485362 , 5201.25644153, 4610.43600698, 3235.48079634,
       5272.49082857, 3074.34335123, 3073.73623997, 2909.71501641,
       4069.550473  , 2908.65257171, 3493.45248634, 4684.09883903,
       5088.63730407, 3946.00333298, 4692.64898918, 3427.53032276,
       3802.4215216 , 3797.51403897, 5284.07653499, 4193.9576873 ,
       3171.43055913, 4199.06754035, 4005.04490235, 5376.00329724,
       4797.02153212, 3311.77444382, 2954.28710091, 4078.91010482,
       3450.54995778, 4105.01588871, 3253.64354133, 3843.04738296,
       3440.43143689, 4967.82216468, 2991.47266517, 4624.50075101,
       3026.93808087, 5160.9341358 , 4631.43193782, 5015.83454629,
       3520.62071492, 5230.95430033, 3214.4848655 , 4366.52906101,
       5284.38009061, 4587.16340894, 5026.91432666, 4265.09088913,
       3995.68527053, 4290.58956176, 3028.25348859, 5079.12589443,
       4059.93787816, 4317.50482732, 5302.13809477, 2940.07057906,
       3341.77585825, 3347.69519297, 3239.27524167, 4735.85507337,
       3995.73586313, 3992.39675124, 3746.26373068, 3725.01483682,
       4099.85544306, 4668.41513166, 3211.90464268, 4715.6686242 ,
       3248.33131787, 4825.90990925, 4982.13987174, 5197.71495922,
       4061.40506369, 3802.52270681, 4238.22621618, 4590.04718739,
       5021.80447361, 5290.40061054, 5347.97499438, 4534.04117429,
       5406.10589688, 4750.42574344, 4550.43317812, 3054.25808727,
       3553.80946342, 4159.35234587, 5264.90193791, 4481.57664349,
       4513.24761387, 3130.70351256, 4516.73850357, 4455.420267  ,
       4879.63925516, 3436.63699156, 4034.54039073, 4967.9739425 ,
       3821.8490817 , 3344.10311806, 3950.35429696, 4665.58194581,
       4832.99287387, 4146.60300955, 3337.27311646, 3496.38685739,
       3679.88623367, 3871.12627842, 5327.94032303, 3519.65945543,
       4215.25717376, 3187.97434078, 4264.83792611, 3913.92762177,
       4785.78997394, 5245.06963697, 4385.04595424, 5017.40291703,
       4821.00242662, 4713.13899398, 4714.35321648, 4267.21577852,
       3560.23472419, 3592.86695405, 3444.98477129, 5269.3540871 ,
       3802.77566983, 5187.1411049 , 3154.83618488, 4139.92478577,
       3286.02280817, 4774.25486013, 3829.03323153, 4122.0655964 ,
       3676.49652917, 5217.59785276, 4284.82200486, 4040.30794764,
       3273.22287925, 3365.25082671, 5178.23680652, 3945.90214777,
       4749.31270614, 4037.575947  , 4668.21276124, 4516.68791097,
       5082.97093237, 2985.40155263, 3594.89065822, 4010.00297758,
       3004.01963107, 5283.92475717, 4111.18818645, 3451.30884685,
       2982.26481116, 5283.0646829 , 4374.42150731, 4901.69763069,
       3994.42045542, 4013.89860813, 4655.66579534, 4854.44413815,
       5225.18674343, 5025.64951155, 3841.63079004, 4609.27237708,
       5345.95129021, 2929.95205818, 3988.65289851, 4165.67642142,
       5123.2932381 , 4945.40964092, 3985.46556444, 5389.86567085,
       4225.9828059 , 3306.71518338, 4526.75583925, 4248.54710748,
       4600.01393047, 3780.31255346, 4651.8207574 , 3072.42083226,
       4146.80537997, 3000.73111178, 3076.87298145, 4450.76574739,
       4477.27627212, 5161.84480268, 3691.82608831, 5055.24618514,
       5366.64366542, 3578.75161741, 3540.55420106, 3992.09319562,
       3598.33095532, 3261.68776544, 3510.60337924, 4290.79193218,
       3543.38738691, 2991.877406  , 3040.80045449, 4255.52888689,
       4413.83314616, 3975.65059918, 3093.36617049, 4145.74293527,
       2909.6644238 , 4312.64793729, 3626.20748037, 5189.4177721 ,
       5015.68276848, 5044.62173821, 4500.80183318, 5297.33179735,
       3599.49458523, 4747.13722415, 3673.81512114, 3523.30212295,
       4882.01710757, 4854.14058253, 3944.58674005, 3751.98069498,
       3449.18395746, 4676.96528181, 4694.31854513, 3022.53652429,
       5307.65268865, 3117.4482502 , 4602.99889413, 3420.64972856,
       4145.74293527, 3145.67892347, 3003.51370502, 3869.45672247,
       3025.82504358, 4351.5536501 , 3893.7411726 , 3021.5246722 ,
       3408.45691089, 4121.10433692, 3112.43958236, 5271.27660607,
       4727.81084926, 3857.01094178, 2966.02458514, 4516.73850357,
       5180.20991809, 5346.45721625, 4792.1646421 , 4074.55914084,
       5208.23822094, 3344.05252545, 3974.48696927, 4898.86444484,
       2951.70687808, 3918.17740054, 5051.50233241, 5006.12076624,
       5381.77085414, 4985.58016884, 2980.4434774 , 3397.52890834,
       3445.89543817, 4911.46200335, 4182.87790693, 4005.85438402,
       2934.40420737, 5038.70240349, 4068.99395435, 3734.98157989,
       3785.37181391, 4786.34649259, 3107.38032192, 4601.27874558,
       5283.97534978, 4627.13156644, 4373.15669219, 3377.59542219,
       3869.50731508, 5137.76272297, 3829.74152799, 3171.22818871,
       4347.0003157 , 4363.69587517, 3009.88837318, 2944.92746909,
       3922.47777192, 4826.16287228, 3815.22145052, 4654.95749888,
       3917.6714745 , 3962.69889244, 4804.25627456, 4254.41584959,
       4571.63147938, 3401.52572409, 3429.30106392, 4542.99606527,
       4716.57929108, 4402.34862495, 3731.49069019, 3920.40347514,
       4627.53630728, 4422.48448152, 4003.02119817, 3347.64460037,
       3095.44046727, 5374.53611171, 4327.26919998, 5212.79155534,
       4383.5281761 , 4535.71073023, 4120.49722566, 3527.75427214,
       4925.22319175, 5095.01197223, 2929.90146557, 4565.66155206,
       4110.32811217, 5228.57644793, 4876.6542915 , 4092.77247843,
       5371.60174065, 4965.49490488, 4951.48075345, 4539.8593238 ,
       4296.10415565, 5242.74237717, 4887.78466447, 4587.92229801,
       5166.75228531, 3160.55314918, 5240.56689518, 5296.57290828,
       4076.88640064, 5216.38363026, 5016.74521317, 5307.34913303,
       3707.56038829, 4893.70399919, 3946.00333298, 3106.62143285,
       4185.25575934, 4720.77847724, 4255.32651647, 4495.13546148,
       4995.85046754, 5260.95571476, 3138.49477365, 4067.93150966,
       2960.00406521, 3008.52237286, 5021.85506622, 5040.37195944,
       5099.46412142, 4941.56460298, 4877.96969921, 3429.25047131,
       4576.03303597, 4209.69198728, 4997.92476432, 3546.52412839,
       4002.71764255, 4350.3900202 , 4380.23965682, 5356.01921849,
       4747.6937428 , 3572.37694925, 4861.72947319, 4632.44378991,
       4370.9812102 , 5267.68453115, 4825.85931665, 3877.55153918,
       4454.45900752, 3772.26832936, 3896.11902501, 4161.12308702,
       5370.03336992, 4665.93609404, 3492.89596769, 4886.46925676,
       3830.85456529, 3944.58674005, 3640.01926138, 4984.26476112,
       3866.06701798, 4574.86940606, 4304.55312059, 3051.07075319,
       3028.91119245, 3833.2830103 , 4528.5265804 , 5266.72327167,
       4256.03481294, 4258.61503576, 4408.82447832, 5390.11863388,
       4211.1085802 , 4781.79315819, 4987.55328041, 3591.29858331,
       4771.97819293, 3306.56340557, 4143.82041631, 3712.87261176,
       3581.73658107, 2918.61931479, 3815.17085792, 3384.12186816,
       4531.61272927, 5207.27696146, 3994.26867761, 3890.3008755 ,
       3911.80273238, 4925.7291178 , 5042.74981185, 4683.99765382,
       3932.24214457, 5066.62952114, 3592.00687977, 4194.56479855,
       4199.47228118, 4914.2951892 , 4112.25063114, 3580.26939554,
       4859.40221339, 3104.29417305, 3905.88339766, 4803.95271893,
       3239.17405646, 4163.95627287, 3234.21598123, 3266.54465546,
       3144.00936753, 3225.51405327, 3836.26797397, 4012.68438562,
       4737.01870327, 4669.57876156, 5088.9914523 , 5145.95872489,
       3809.2009306 , 3663.39304462, 5205.30384989, 3056.13001363,
       4392.07832625, 3655.0958575 , 4890.71903553, 3225.66583108,
       4357.06824399, 4316.64475304, 4819.43405589, 3698.04897866,
       3575.2607277 , 3618.46681189, 4216.87613711, 4797.42627296,
       4676.40876316, 3449.18395746, 5346.35603104, 3178.81707938,
       4806.07760832, 3749.50165737, 5370.74166638, 5054.53788868,
       5389.35974481, 4250.62140426, 3464.05818316, 5238.84674662,
       2968.04828931, 3818.45937721, 4025.48431454, 4785.2840479 ,
       4782.75441767, 4294.13104407, 5395.93678339, 4002.56586473,
       3682.36527129, 3303.32547888, 4081.08558681, 3007.05518733,
       5292.2725369 , 4705.04417727, 3912.96636228, 5218.71089006,
       5231.91555982, 2992.48451726, 3418.42365397, 5379.24122392,
       2975.94073561, 3486.97663297, 3516.11797312, 4309.20764019,
       3487.93789245, 4838.91220859, 4516.23257753, 4213.28406219,
       5304.26298415, 5184.05495603, 3195.56323144, 4716.57929108,
       5370.74166638, 4486.38294091, 4589.08592791, 3033.51511945,
       4838.15331953, 3611.33325466, 3506.30300786, 3385.18431285,
       4095.8080347 , 5290.80535138, 3738.82661783, 4219.50695254,
       3604.50325306, 3349.56711933, 4219.60813774, 4609.4747475 ,
       4852.42043398, 3141.27736689, 4395.11388252, 4175.7443497 ,
       4224.97095381, 5261.81578904, 3971.65378343, 4515.22072544,
       3481.36085388, 4606.38859862, 3002.95718637, 3243.42383524,
       4432.24885417, 4328.6857929 , 3728.45513392, 4561.81651412,
       4165.01871756, 5313.47083816, 4721.94210715, 5327.13084136,
       4343.71179642, 5161.44006184, 4462.14908339, 5181.42414059,
       4419.85366609, 4543.50199132, 4507.37887175, 4957.40008817,
       4168.30723685, 4734.03373961, 3298.62036667, 3519.3053072 ,
       3731.5918754 , 3011.55792913, 5296.11757484, 3391.55898101,
       3057.19245832, 4252.13918239, 4226.58991716, 4983.91061289,
       4072.83899229, 5350.20106898, 3479.23596449, 4118.92885493,
       4791.0010122 , 3891.97043145, 3364.23897462, 5020.43847329,
       3664.65785973, 3479.18537189, 4833.85294815, 3040.9016397 ,
       4763.42804278, 4765.19878394, 4086.85314372, 5406.71300813,
       3590.13495341, 5069.86744782, 4249.9131078 , 5184.25732644,
       3705.23312849, 4516.38435534, 3418.22128355, 3191.92056392,
       5239.04911704, 4110.6316678 , 4658.95431463, 4043.39409651,
       2917.55687009, 4447.57841331, 4520.58354151, 3829.64034279,
       3802.06737337, 4161.07249442, 3645.17970703, 4571.93503501,
       5141.60776091, 3014.54289279, 5158.20213516, 4759.0264862 ,
       5238.84674662, 5020.33728808, 4582.35711152, 4443.78396798,
       4261.14466598, 5154.00294899, 4642.46112558, 3067.71572005,
       2934.65717039, 3544.65220202, 5176.11191713, 3257.74154229,
       5250.98897169, 4536.67198972, 3127.21262286, 5364.72114645,
       3425.75958161, 4930.02948917, 5132.65286992, 4781.03426912,
       3355.94178749, 3420.49795075, 4398.09884618, 4989.52639199,
       3907.4011758 , 3201.58375137, 4425.52003778, 3916.30547418,
       4921.32756121, 3674.92815843, 3796.7045573 , 3899.71109992,
       3298.16503323, 3066.45090493, 3403.29646524, 4392.28069667,
       5023.11988133, 4579.47333307, 4240.55347598, 3096.30054155,
       4253.40399751, 4092.21595979, 3729.77054164, 3767.81618017,
       3507.36545256, 4301.3151939 , 5250.28067523, 5377.36929756,
       4196.43672492, 3146.48840515, 3669.9194906 , 4794.4919019 ,
       4170.83686707, 5192.20036534, 4684.25061685, 4233.36932615,
       4636.08645743, 3311.62266601, 4485.52286664, 4530.09495114,
       5327.5861748 , 5152.68754128, 3588.71836048, 4229.47369561,
       3478.67944584, 3466.03129474, 3362.56941867, 2920.44064854,
       3384.77957202, 3560.386502  , 3657.11956167, 3737.00528407,
       3472.30477769, 4543.19843569, 5386.52655896, 5347.0643275 ,
       5010.62350803, 4495.99553575, 4006.46149527, 5405.54937823,
       3148.86625755, 5150.30968887, 4251.98740458, 3680.44275232,
       3375.01519936, 5272.28845815, 5346.20425323, 3690.71305102,
       3413.97150478, 4775.82323087, 4532.21984053, 4171.39338572,
       4730.94759074, 4814.93131409, 4340.37268452, 3368.79230902,
       4238.93451264, 2949.98672953, 4854.44413815, 2995.82362915,
       4268.53118623, 3910.8920655 , 4578.96740702, 3793.87137145,
       3369.19704985, 3714.44098249, 4624.29838059, 4711.36825282,
       4449.50093228, 3940.03340566, 3955.97007605, 3074.79868467,
       3475.13796353, 3257.94391271, 4868.86303042, 5111.30279085,
       4383.62936131, 3987.3880834 , 5284.43068322, 3239.5282047 ,
       3745.85898985, 3497.5504873 , 5023.06928872, 3330.13955923,
       3980.35571139, 3914.88888125, 3914.07939958, 3003.00777898,
       2930.91331766, 4346.69676008, 3136.01573603, 4745.31589039,
       4410.03870083, 5345.69832718, 5323.53876644, 4643.37179246,
       3145.17299743, 3678.82378898, 4204.17739339, 3607.53880933,
       3494.97026447, 4879.58866256, 3300.39110783, 3678.06489991])

In [5]:
#multiple linear Regression

In [6]:
df2=pd.read_csv(r"C:\Users\LENOVO\Downloads\Multiple Linear Regression.csv")
df2.head()

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [7]:
x1=df2[["Engine Size(L)","Cylinders","Fuel Consumption City (L/100 km)","Fuel Consumption Hwy (L/100 km)","Fuel Consumption Comb (L/100 km)","Fuel Consumption Comb (mpg)"]]
y1=df2["CO2 Emissions(g/km)"]
model1=LinearRegression()
model1.fit(x1,y1)
prediction1=model1.predict(x1)
prediction1

array([199.13137746, 221.12283473, 136.98347218, ..., 231.17317105,
       222.32167533, 235.70305162], shape=(7385,))